---
- name: Add HashiCorp apt repo key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp apt repo
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_lsb['codename'] }} main"
    state: present

- name: Install Consul
  apt:
    name: consul
    state: latest
