---
- name: Supply CA certificate
  copy:
    src: "{{ consul_ca_file_internal }}"
    dest: "{{ consul_config_dir }}/consul-agent-ca.pem"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
  notify:
      - restart consul
