---
- name: Create certificate authority
  include_role:
    name: peaceman.pki
    tasks_from: ca.yml

- name: Generate nss server certificate that is shared between all edge nodes
  include_role:
    name: peaceman.pki
    tasks_from: cert.yml
  vars:
    cert_name: nss-edge-node

- name: Create nss client certs for hosts in group {{ nss_client_certs_group_name }}
  include_role:
    name: peaceman.pki
    tasks_from: cert.yml
  vars:
    cert_name: nss-{{ ihs }}
  loop: >
    {{
      groups[nss_client_certs_group_name]
      | default([])
      | map('extract', hostvars, ['inventory_hostname_short'])
      | list
    }}
  loop_control:
    loop_var: ihs
