---
- name: Copy CA certificate to node via paths
  copy:
    src: "{{ node_exporter_ca_file | mandatory }}"
    dest: /etc/node_exporter/ca.cert
  notify:
    - restart node_exporter

- name: Copy node exporter certs to node via paths
  copy:
    src: "{{ item.src }}"
    dest: "/etc/node_exporter/{{ item.dest }}"
  loop:
    - dest: tls.cert
      src: "{{ node_exporter_cert_file | mandatory }}"
    - dest: tls.key
      src: "{{ node_exporter_cert_key_file | mandatory }}"
  notify:
    - restart node_exporter
